apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: snowballresources.snowball.com
spec:
  group: snowball.com
  version: v1
  names:
    kind: SnowballResource
    plural: snowballresources
  scope: Namespaced
