/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	snowballresourcev1 "github.com/robel-yemane/snowball-controller/pkg/apis/snowballresource/v1"
	versioned "github.com/robel-yemane/snowball-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/robel-yemane/snowball-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/robel-yemane/snowball-controller/pkg/client/listers/snowballresource/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SnowballResourceInformer provides access to a shared informer and lister for
// SnowballResources.
type SnowballResourceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.SnowballResourceLister
}

type snowballResourceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSnowballResourceInformer constructs a new informer for SnowballResource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSnowballResourceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSnowballResourceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSnowballResourceInformer constructs a new informer for SnowballResource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSnowballResourceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SnowballV1().SnowballResources(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SnowballV1().SnowballResources(namespace).Watch(options)
			},
		},
		&snowballresourcev1.SnowballResource{},
		resyncPeriod,
		indexers,
	)
}

func (f *snowballResourceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSnowballResourceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *snowballResourceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&snowballresourcev1.SnowballResource{}, f.defaultInformer)
}

func (f *snowballResourceInformer) Lister() v1.SnowballResourceLister {
	return v1.NewSnowballResourceLister(f.Informer().GetIndexer())
}
