/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/robel-yemane/snowball-controller/pkg/apis/snowballresource/v1"
	scheme "github.com/robel-yemane/snowball-controller/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SnowballResourcesGetter has a method to return a SnowballResourceInterface.
// A group's client should implement this interface.
type SnowballResourcesGetter interface {
	SnowballResources(namespace string) SnowballResourceInterface
}

// SnowballResourceInterface has methods to work with SnowballResource resources.
type SnowballResourceInterface interface {
	Create(*v1.SnowballResource) (*v1.SnowballResource, error)
	Update(*v1.SnowballResource) (*v1.SnowballResource, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.SnowballResource, error)
	List(opts metav1.ListOptions) (*v1.SnowballResourceList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.SnowballResource, err error)
	SnowballResourceExpansion
}

// snowballResources implements SnowballResourceInterface
type snowballResources struct {
	client rest.Interface
	ns     string
}

// newSnowballResources returns a SnowballResources
func newSnowballResources(c *SnowballV1Client, namespace string) *snowballResources {
	return &snowballResources{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the snowballResource, and returns the corresponding snowballResource object, and an error if there is any.
func (c *snowballResources) Get(name string, options metav1.GetOptions) (result *v1.SnowballResource, err error) {
	result = &v1.SnowballResource{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("snowballresources").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SnowballResources that match those selectors.
func (c *snowballResources) List(opts metav1.ListOptions) (result *v1.SnowballResourceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.SnowballResourceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("snowballresources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested snowballResources.
func (c *snowballResources) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("snowballresources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a snowballResource and creates it.  Returns the server's representation of the snowballResource, and an error, if there is any.
func (c *snowballResources) Create(snowballResource *v1.SnowballResource) (result *v1.SnowballResource, err error) {
	result = &v1.SnowballResource{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("snowballresources").
		Body(snowballResource).
		Do().
		Into(result)
	return
}

// Update takes the representation of a snowballResource and updates it. Returns the server's representation of the snowballResource, and an error, if there is any.
func (c *snowballResources) Update(snowballResource *v1.SnowballResource) (result *v1.SnowballResource, err error) {
	result = &v1.SnowballResource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("snowballresources").
		Name(snowballResource.Name).
		Body(snowballResource).
		Do().
		Into(result)
	return
}

// Delete takes name of the snowballResource and deletes it. Returns an error if one occurs.
func (c *snowballResources) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("snowballresources").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *snowballResources) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("snowballresources").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched snowballResource.
func (c *snowballResources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.SnowballResource, err error) {
	result = &v1.SnowballResource{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("snowballresources").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
